---
# Install firewalld, so I can open ports
- name: Install firewalld and open port 80
  hosts: all
  sudo: yes

  tasks:
    - name: Install firewalld
      yum: name=firewalld state=latest

    - name: Start firewalld
      service: name=firewalld state=started enabled=yes

    - name: Insert firewalld rule for nginx
      firewalld: port=80/tcp permanent=true state=enabled immediate=yes

    - name: Restart firewalld
      service: name=firewalld state=restarted enabled=yes
