---
# This playbook will copy files from git to respective directories

  - name: Add www directory in /usr/share/nginx/
    file:
      path: /usr/share/nginx/www/
      state: directory
      owner: iwasakik@msuoc.net
      mode: 0775 # "u=rwx, g=r, o=r"

    ignore_errors: true
    changed_when: false
    #check_mode: no
    register: add_directory

  - debug: var=add_directory

  - name: Pull the html file to the www directory
    git: repo={{ repository }} dest=/usr/share/nginx/www update=yes

    #ignore_errors: true
    #register: git_html
    #when: add_directory.failed == false

  - name: Set boolean true if something failed
    set_fact: failed_git_code=true
    #when: add_directory.failed == true or git_html.failed == true
