---
# Install, start and enable firewalld and then open port 80 for Nginx

  - name: Install firewalld
    yum: name=firewalld state=latest

  - name: Start firewalld
    service: name=firewalld state=started enabled=yes

  - name: Insert firewalld rule for nginx
    firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes

  - name: Restart firewalld
    service: name=firewalld state=restarted enabled=yes
