---
# This playbook will create a snapshot of the volume

  - name: Gather facts about this ec2 instance
    action: ec2_facts

# Testing
#  - name: Conditional
#    action: debug msg="This instance is a t2.micro"
#    when: ansible_ec2_instance_type == "t2.micro"
#  - name: Conditional 2
#    action: debug msg="{{ansible_ec2_instance_id}}"

  - name: Create a variable for instance_id
    set_fact: i_id="{{ ansible_ec2_instance_id }}"

  - name: Extract tags aka the name of the instance
    ec2_tag:
      resource: "{{ansible_ec2_instance_id}}"
      region: "{{ ansible_ec2_placement_region }}"
      aws_access_key: "{{ akey }}"
      aws_secret_key: "{{ pkey }}"
      state: list
    register: instance_tags

#  - debug: var=instance_tags

  - name: Create a snapshot of an instance
    ec2_snapshot:
      aws_access_key: "{{ akey }}"
      aws_secret_key: "{{ pkey }}"
      region: "{{ aws_region }}"
      instance_id: "{{ i_id }}"
      description: "AWS backup snapshot taken on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}"
      device_name: "{{instance_tags.tags.Name}}"
      snapshot_tags:
        Name: "{{ instance_tags.tags.Name }} ({{ ansible_ec2_block_device_mapping_ami }})"

    - name: Extract snapshot id
      ec2_snapshot_facts:
        aws_access_key: "{{ akey }}"
        aws_secret_key: "{{ pkey }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name":"{{ instance_tags.tags.Name }} ({{ ansible_ec2_block_device_mapping_ami }})"
      register: snapshots_info
