---
# This playbook will create a snapshot of the volume

  - name: Gather facts about this ec2 instance
    action: ec2_facts

# Testing
#  - name: Conditional
#    action: debug msg="This instance is a t2.micro"
#    when: ansible_ec2_instance_type == "t2.micro"
#  - name: Conditional 2
#    action: debug msg="{{ansible_ec2_instance_id}}"

  - name: Create a variable for instance_id
    set_fact: i_id="{{ ansible_ec2_instance_id }}"

  - name: Create a snapshot of an instance
    ec2_snapshot:
      aws_access_key: "{{ akey }}"
      aws_secret_key: "{{ pkey }}"
      region: "{{ aws_region }}"
      instance_id: "{{ i_id }}"
#      volume_id: vol-07de2f7eeede26afd
      description: AWS backup snapshot taken on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}
#      device_name: "{{ec2_tags.tags.Name}}"
#      ec2_tags:
