---
# This playbook will stop the instance, detach the old volume,
# create and attach the new volume, and restart the instance

  - ec2_remote_facts:
      filters:
        instance-state-name: running
        "tag:Name": MSURHEL2
        
  - name: Stop the instance
    ec2:
      aws_secret_key: "{{ pkey }}"
      aws_access_key: "{{ akey }}"
      region: {{ aws_region }}
      instance_ids: "{{ instance_id }}"
      state: stopped
      wait: yes

  - name: Detach the old volume
    ec2_vol:
      aws_secret_key: "{{ pkey }}"
      aws_access_key: "{{ akey }}"
      region: {{ aws_region }}
      id: "{{ volume_id }}"
      instance: None
  #        register: detach_vol

  - name: Creating a new volume from a snapshot
    ec2_vol:
      aws_secret_key: "{{ pkey }}"
      aws_access_key: "{{ akey }}"
      snapshot: "{{ snapshot_id }}"
      region: {{ aws_region }}
      volume_type: gp2
      instance: "{{ instance_id }}"
      device_name: /dev/sda1
  #        volume_size: 60
    register: ec2_vol
  #        tags: attach

  - name: Attach the Created volume to an instance
    ec2_vol:
      aws_secret_key: "{{ pkey }}"
      aws_access_key: "{{ akey }}"
      region: {{ aws_region }}
      instance: "{{ instance_id }}"
      id: "{{ ec2_vol.volume_id }}"
      device_name: /dev/sda1

  - name: Start the instance
    ec2:
      aws_secret_key: "{{ pkey }}"
      aws_access_key: "{{ akey }}"
      region: {{ aws_region }}
      instance_ids: "{{ instance_id }}"
      state: running
