---
# Playbook to deploy a website to Windows servers.
# Doing this so database servers can be added in the future.
# Koshiro Iwasaki

  - name: Apply common configurations to all nodes
    hosts: windows1
    # Define this so that ansible knows that this playbook is using Windows servers.
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    gather_facts: false

    roles:
      - common

  - name: Configure and deploy the webserver
    hosts: windows1
    # Define this so that ansible knows that this playbook is using Windows servers.
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    gather_facts: false

    roles:
      - web

#  - name: Configure and deploy the database server
#    hosts: dbservers
#
#    roles:
#      - db

#  - name: In case of emergencies, revert to previous state
#    hosts: all
#
#    roles:
#      - emergency
